apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-counter-claim
  namespace: exercises
spec:
  storageClassName: ping-pong-counter-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
