apiVersion: v1
kind: PersistentVolume
metadata:
  name: ping-pong-counter-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ping-pong-counter-storage
  local:
    path: /tmp/ping-pong-counter
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
