apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-generator
              image: todo-generator:2.9
              imagePullPolicy: IfNotPresent
